// <auto-generated />
using GestioneRubrica_Week8_MariaDeStefano_EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestioneRubrica_Week8_MariaDeStefano_EF.Migrations
{
    [DbContext(typeof(RubricaContext))]
    partial class RubricaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GestioneRubrica_Week8_MariaDeStefano_Core.Entities.Contatto", b =>
                {
                    b.Property<int>("IDContatto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDContatto"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDContatto");

                    b.ToTable("Contatto", (string)null);
                });

            modelBuilder.Entity("GestioneRubrica_Week8_MariaDeStefano_Core.Entities.Indirizzo", b =>
                {
                    b.Property<int>("IDIndirizzo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDIndirizzo"), 1L, 1);

                    b.Property<string>("CAP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Città")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDContatto")
                        .HasColumnType("int");

                    b.Property<string>("Nazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipologia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDIndirizzo");

                    b.HasIndex("IDContatto");

                    b.ToTable("Indirizzo", (string)null);
                });

            modelBuilder.Entity("GestioneRubrica_Week8_MariaDeStefano_Core.Entities.Indirizzo", b =>
                {
                    b.HasOne("GestioneRubrica_Week8_MariaDeStefano_Core.Entities.Contatto", "Contatto")
                        .WithMany("Indirizzi")
                        .HasForeignKey("IDContatto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contatto");
                });

            modelBuilder.Entity("GestioneRubrica_Week8_MariaDeStefano_Core.Entities.Contatto", b =>
                {
                    b.Navigation("Indirizzi");
                });
#pragma warning restore 612, 618
        }
    }
}
